//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebModuleApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModuleAppDEMO2Entities : DbContext
    {
        public ModuleAppDEMO2Entities()
            : base("name=ModuleAppDEMO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FilterUser> FilterUsers { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<SemesterModule> SemesterModules { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<StudyRecord> StudyRecords { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
